# Generated by Django 2.2 on 2021-02-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
                ('easy_saver_balance', models.FloatField(default=0)),
                ('loan_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('Deposit', 'deposit'), ('Withdrawal', 'withdrawal'), ('Savings', 'savings')], max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'confirmed'), ('Declined', 'Declined')], max_length=10)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User')),
            ],
        ),
    ]
