# Generated by Django 2.2 on 2021-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210221_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profile_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='total_balance',
            field=models.FloatField(default=0),
        ),
    ]
